# This workflow will test a Cucumber Java project with Maven.

name: Java CI/CD with npm cypress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Windows-Run:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests on Chrome headless
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
    